Ensure compilers are installed (#7)
This change adds additional checks to ensure the compilers are correctly installed.

* A version check is performed to verify that the desired GCC or Clang version is present.
* Each built Docker image compile and execute an example Conan CMake project.

Several additional changes were also made to (i) make the images consistent with each other, (ii) remove extraneous files, and (iii) remove packages that will be moved into the tools image(s).

diff --git a/docker/debian/Dockerfile b/docker/debian/Dockerfile
--- a/docker/debian/Dockerfile
+++ b/docker/debian/Dockerfile
@@ -13,36 +13,34 @@ FROM gcc:${GCC_VERSION}-${DEBIAN_VERSION} AS gcc-src
 # ====================== BASE IMAGE ======================
 FROM debian:${DEBIAN_VERSION} AS base
 
-# Use Bash as the default shell for RUN commands and as the entrypoint.
-SHELL ["/bin/bash", "-c"]
+# Use Bash as the default shell for RUN commands, using the options
+# `set -o errexit -o pipefail`, and as the entrypoint.
+SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]
 ENTRYPOINT ["/bin/bash"]
 
 # Ensure any packages installed directly or indirectly via dpkg do not require
 # manual interaction.
 ARG DEBIAN_FRONTEND=noninteractive
 RUN <<EOF
-set -ex
 ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
-apt update
-apt upgrade -y
-apt install -y tzdata
-apt clean
+apt-get update
+apt-get upgrade -y
+apt-get install -y --no-install-recommends tzdata
+apt-get clean
 rm -rf /var/lib/apt/lists/*
 dpkg-reconfigure --frontend noninteractive tzdata
 EOF
 
-# Install tools that are shared by all stages. Run `apt update` again before
+# Install tools that are shared by all stages. Run `apt-get update` again before
 # installing the packages to ensure the package lists are up-to-date, which is
 # especially important when the image is built from a cached layer.
 RUN <<EOF
 pkgs=()
-pkgs+=(bison)           # Required build tool.
 pkgs+=(ca-certificates) # Enable TLS verification for HTTPS connections by providing trusted root certificates.
 pkgs+=(cmake)           # Required build tool.
 pkgs+=(curl)            # Dependency for tools requiring downloading data.
 pkgs+=(dpkg-dev)        # Required packaging tool.
 pkgs+=(file)            # Required packaging tool.
-pkgs+=(flex)            # Required build tool.
 pkgs+=(git)             # Required build tool.
 pkgs+=(gpg)             # Dependency for tools requiring signing or encrypting/decrypting.
 pkgs+=(jq)              # Pretty printing.
@@ -50,9 +48,9 @@ pkgs+=(libc6-dev)       # Required build tool.
 pkgs+=(ninja-build)     # Required build tool.
 pkgs+=(pipx)            # Package manager for Python applications.
 pkgs+=(wget)            # Required build tool.
-apt update
-apt install -y --no-install-recommends "${pkgs[@]}"
-apt clean
+apt-get update
+apt-get install -y --no-install-recommends "${pkgs[@]}"
+apt-get clean
 rm -rf /var/lib/apt/lists/*
 EOF
 
@@ -72,12 +70,14 @@ RUN useradd -ms /bin/bash ${NONROOT_USER}
 # ====================== GCC IMAGE ======================
 FROM base AS gcc
 
+# This is not inherited from base image, ensure no manual interaction needed.
+ARG DEBIAN_FRONTEND=noninteractive
+
 # Copy GCC from the source image, make the package manager aware of its
 # existence, and create the necessary symlinks.
 COPY --from=gcc-src /usr/local/ /usr/local/
 COPY --from=gcc-src /etc/ld.so.conf.d/*.conf /etc/ld.so.conf.d/
 RUN <<EOF
-set -ex
 ldconfig -v
 dpkg-divert --divert /usr/bin/gcc.orig --rename /usr/bin/gcc
 dpkg-divert --divert /usr/bin/g++.orig --rename /usr/bin/g++
@@ -99,12 +99,35 @@ EOF
 ENV CC=/usr/bin/gcc
 ENV CXX=/usr/bin/g++
 
+# Check that the installed GCC version matches the expected version. We must
+# repeat the GCC_VERSION argument here, as it is not inherited from the source
+# image.
+ARG GCC_VERSION
+RUN <<EOF
+CC_VER=$(${CC} -dumpversion)
+CC_VER=${CC_VER%%.*}
+if [[ "${CC_VER}" != "${GCC_VERSION}" ]]; then
+  echo "ERROR: 'gcc -dumpversion' gives '${CC_VER}', which does not match expected version '${GCC_VERSION}'."
+  exit 1
+fi
+CXX_VER=$(${CXX} -dumpversion)
+CXX_VER=${CXX_VER%%.*}
+if [[ "${CXX_VER}" != "${GCC_VERSION}" ]]; then
+  echo "ERROR: g++ -dumpversion gives '${CXX_VER}', which does not match expected version '${GCC_VERSION}'."
+  exit 1
+fi
+EOF
+
 # Switch to the non-root user.
 USER ${NONROOT_USER}
 WORKDIR /home/${NONROOT_USER}
 
 # Create a default Conan profile.
-RUN conan profile detect
+RUN <<EOF
+conan profile detect
+rm -rf /tmp/*
+EOF
+
 # Fix the C++ dialect.
 RUN sed -i -e 's|^compiler\.cppstd=.*$|compiler.cppstd=20|' ~/.conan2/profiles/default
 # Explicitly set the compiler flags.
@@ -117,34 +140,63 @@ EOF
 # Print the Conan profile to verify the configuration.
 RUN conan profile show
 
+# Test the image by compiling a simple C++ program.
+RUN --mount=type=bind,source=test,target=/test,readonly <<EOF
+cp -r /test test
+cd test && ./run.sh && cd ..
+rm -rf test
+EOF
+
 # ===================== CLANG IMAGE =====================
 FROM base AS clang
 
+# This is not inherited from base image, ensure no manual interaction needed.
+ARG DEBIAN_FRONTEND=noninteractive
+
 # Install Clang. Use the LLVM apt repository to access the latest versions. We
 # must repeat the DEBIAN_VERSION argument here, as it is not inherited from the
-# base image.
+# base or source images.
 ARG DEBIAN_VERSION
 ARG CLANG_VERSION
 RUN <<EOF
-set -ex
 curl --no-progress-meter https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor -o /etc/apt/keyrings/llvm.gpg
 printf "%s\n%s\n" \
   "deb [signed-by=/etc/apt/keyrings/llvm.gpg] https://apt.llvm.org/${DEBIAN_VERSION}/ llvm-toolchain-${DEBIAN_VERSION}-${CLANG_VERSION} main" \
   | tee /etc/apt/sources.list.d/llvm.list
-apt update
-apt install -t llvm-toolchain-${DEBIAN_VERSION}-${CLANG_VERSION} -y --no-install-recommends clang-${CLANG_VERSION} llvm-${CLANG_VERSION}
-apt clean
+apt-get update
+apt-get install -t llvm-toolchain-${DEBIAN_VERSION}-${CLANG_VERSION} -y --no-install-recommends clang-${CLANG_VERSION} llvm-${CLANG_VERSION}
+apt-get clean
 rm -rf /var/lib/apt/lists/*
 EOF
 ENV CC=/usr/bin/clang-${CLANG_VERSION}
 ENV CXX=/usr/bin/clang++-${CLANG_VERSION}
+
+# Check that the installed Clang version matches the expected version.
+RUN <<EOF
+CC_VER=$(${CC} -dumpversion)
+CC_VER=${CC_VER%%.*}
+if [[ "${CC_VER}" != "${CLANG_VERSION}" ]]; then
+  echo "ERROR: 'clang -dumpversion' gives '${CC_VER}', which does not match expected version '${CLANG_VERSION}'."
+  exit 1
+fi
+CXX_VER=$(${CXX} -dumpversion)
+CXX_VER=${CXX_VER%%.*}
+if [[ "${CXX_VER}" != "${CLANG_VERSION}" ]]; then
+  echo "ERROR: clang++ -dumpversion gives '${CXX_VER}', which does not match expected version '${CLANG_VERSION}'."
+  exit 1
+fi
+EOF
 
 # Switch to the non-root user.
 USER ${NONROOT_USER}
 WORKDIR /home/${NONROOT_USER}
 
 # Create a default Conan profile.
-RUN conan profile detect
+RUN <<EOF
+conan profile detect
+rm -rf /tmp/*
+EOF
+
 # Fix the C++ dialect.
 RUN sed -i -e 's|^compiler\.cppstd=.*$|compiler.cppstd=20|' ~/.conan2/profiles/default
 # Explicitly set the compiler flags. To ensure compatibility with a range of
@@ -152,15 +204,13 @@ RUN sed -i -e 's|^compiler\.cppstd=.*$|compiler.cppstd=20|' ~/.conan2/profiles/d
 # of Clang.
 # TODO: Move extra flags into the rippled repository as a custom Conan profile.
 RUN <<EOF
+CXX_VER=$(${CXX} -dumpversion)
+CXX_VER=${CXX_VER%%.*}
 cat >>~/.conan2/profiles/default <<EOT
 [conf]
 tools.build:compiler_executables={"c": "${CC}", "cpp": "${CXX}"}
 EOT
-if [[ $(clang-${CLANG_VERSION} --version | head -1 | grep -Po 'version \K[0-9]{2}') -ge 20 ]]; then
-    cat >>~/.conan2/profiles/default <<EOT
-tools.build:cxxflags=['-Wno-missing-template-arg-list-after-template-kw', '-Wno-deprecated-declarations']
-EOT
-elif [[ $(clang-${CLANG_VERSION} --version | head -1 | grep -Po 'version \K[0-9]{2}') -eq 19 ]]; then
+if [[ ${CXX_VER} -ge 19 ]]; then
     cat >>~/.conan2/profiles/default <<EOT
 tools.build:cxxflags=['-Wno-missing-template-arg-list-after-template-kw']
 EOT
@@ -168,3 +218,10 @@ fi
 EOF
 # Print the Conan profile to verify the configuration.
 RUN conan profile show
+
+# Test the image by compiling a simple C++ program.
+RUN --mount=type=bind,source=test,target=/test,readonly <<EOF
+cp -r /test test
+cd test && ./run.sh && cd ..
+rm -rf test
+EOF
diff --git a/docker/rhel/Dockerfile b/docker/rhel/Dockerfile
--- a/docker/rhel/Dockerfile
+++ b/docker/rhel/Dockerfile
@@ -1,21 +1,14 @@
-# We want to use the subscription-free Red Hat UBI images, but those only
-# provide a subset of the packages available in the full Red Hat Enterprise
-# Linux (RHEL) distribution. To get some of the packages we need, we use those
-# provided by the Rocky Linux project, which is a community-developed operating
-# system designed to be a 100% bug-for-bug compatible alternative to RHEL.
-ARG RHEL_VERSION
-FROM rockylinux/rockylinux:${RHEL_VERSION%.*} AS rocky
-RUN dnf -y install bison flex
-
 # ====================== BASE IMAGE ======================
+ARG RHEL_VERSION
 FROM registry.redhat.io/ubi${RHEL_VERSION%.*}/s2i-base:${RHEL_VERSION} AS base
 
-# Use Bash as the default shell for RUN commands and as the entrypoint.
-SHELL ["/bin/bash", "-c"]
+# Use Bash as the default shell for RUN commands, using the options
+# `set -o errexit -o pipefail`, and as the entrypoint.
+SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]
 ENTRYPOINT ["/bin/bash"]
 
 # Update the packages installed on the system.
-RUN dnf -y update-minimal --security --sec-severity=Important --sec-severity=Critical
+RUN dnf update-minimal -y --security --sec-severity=Important --sec-severity=Critical
 
 # Install tools that are shared by all stages.
 RUN <<EOF
@@ -34,13 +27,9 @@ pkgs+=(rpm-build)        # Required packaging tool.
 pkgs+=(rpmdevtools)      # Required packaging tool.
 pkgs+=(wget)             # Required build tool.
 dnf install -y --setopt=tsflags=nodocs "${pkgs[@]}"
-dnf -y clean all
+dnf clean -y all
 rm -rf /var/cache/dnf/*
 EOF
-
-# Copy Bison and Flex from the Rocky Linux image.
-COPY --from=rocky /usr/bin/bison /usr/bin/bison
-COPY --from=rocky /usr/bin/flex /usr/bin/flex
 
 # Install Python-based tools.
 ARG CONAN_VERSION
@@ -54,15 +43,43 @@ RUN useradd -ms /bin/bash ${NONROOT_USER}
 # ====================== GCC IMAGE ======================
 FROM base AS gcc
 
-# Install GCC.
+# Install GCC. Red Hat installs GCC as a Software Collection (SCL) package,
+# where typically you would run `scl enable gcc-toolset-X` to open another Bash
+# shell with the GCC toolset enabled. To avoid having to do so, we delete the
+# default GCC packages first, and then reference the GCC toolset binaries
+# directly.
 ARG GCC_VERSION
 RUN <<EOF
+dnf remove -y gcc gcc-c++
 dnf install -y --setopt=tsflags=nodocs gcc-toolset-${GCC_VERSION}-gcc gcc-toolset-${GCC_VERSION}-gcc-c++
-dnf -y clean all
+dnf clean -y all
 rm -rf /var/cache/dnf/*
+update-alternatives \
+    --install /usr/bin/gcc gcc /opt/rh/gcc-toolset-${GCC_VERSION}/root/usr/bin/gcc ${GCC_VERSION} \
+    --slave /usr/bin/g++ g++ /opt/rh/gcc-toolset-${GCC_VERSION}/root/usr/bin/g++ \
+    --slave /usr/bin/cpp cpp /opt/rh/gcc-toolset-${GCC_VERSION}/root/usr/bin/cpp \
+    --slave /usr/bin/gcov gcov /opt/rh/gcc-toolset-${GCC_VERSION}/root/usr/bin/gcov \
+    --slave /usr/bin/gcov-dump gcov-dump /opt/rh/gcc-toolset-${GCC_VERSION}/root/usr/bin/gcov-dump-${GCC_VERSION} \
+    --slave /usr/bin/gcov-tool gcov-tool /opt/rh/gcc-toolset-${GCC_VERSION}/root/usr/bin/gcov-tool-${GCC_VERSION}
 EOF
 ENV CC=/usr/bin/gcc
 ENV CXX=/usr/bin/g++
+
+# Check that the installed GCC version matches the expected version.
+RUN <<EOF
+CC_VER=$(${CC} -dumpversion)
+CC_VER=${CC_VER%%.*}
+if [[ "${CC_VER}" != "${GCC_VERSION}" ]]; then
+  echo "ERROR: 'gcc -dumpversion' gives '${CC_VER}', which does not match expected version '${GCC_VERSION}'."
+  exit 1
+fi
+CXX_VER=$(${CXX} -dumpversion)
+CXX_VER=${CXX_VER%%.*}
+if [[ "${CXX_VER}" != "${GCC_VERSION}" ]]; then
+  echo "ERROR: g++ -dumpversion gives '${CXX_VER}', which does not match expected version '${GCC_VERSION}'."
+  exit 1
+fi
+EOF
 
 # Switch to the non-root user.
 USER ${NONROOT_USER}
@@ -73,7 +90,11 @@ WORKDIR /home/${NONROOT_USER}
 ENV CONAN_HOME=/home/${NONROOT_USER}/.conan2
 
 # Create a default Conan profile.
-RUN conan profile detect
+RUN <<EOF
+conan profile detect
+rm -rf /tmp/*
+EOF
+
 # Fix the C++ dialect.
 RUN sed -i -e 's|^compiler\.cppstd=.*$|compiler.cppstd=20|' ${CONAN_HOME}/profiles/default
 # Explicitly set the compiler flags.
@@ -86,6 +107,13 @@ EOF
 # Print the Conan profile to verify the configuration.
 RUN conan profile show
 
+# Test the image by compiling a simple C++ program.
+RUN --mount=type=bind,source=test,target=/test,readonly <<EOF
+cp -r /test test
+cd test && ./run.sh && cd ..
+rm -rf test
+EOF
+
 # ===================== CLANG IMAGE =====================
 FROM base AS clang
 
@@ -93,11 +121,28 @@ FROM base AS clang
 # to install and we get what is available.
 RUN <<EOF
 dnf install -y --setopt=tsflags=nodocs clang llvm
-dnf -y clean all
+dnf clean -y all
 rm -rf /var/cache/dnf/*
 EOF
 ENV CC=/usr/bin/clang
 ENV CXX=/usr/bin/clang++
+
+# Check that the installed Clang version is not older than the minimum required.
+ARG MINIMUM_CLANG_VERSION=16
+RUN <<EOF
+CC_VER=$(${CC} -dumpversion)
+CC_VER=${CC_VER%%.*}
+if [[ ${CC_VER} -lt ${MINIMUM_CLANG_VERSION} ]]; then
+  echo "ERROR: 'clang -dumpversion' gives '${CC_VER}', which is less than minimum required '${MINIMUM_CLANG_VERSION}'."
+  exit 1
+fi
+CXX_VER=$(${CXX} -dumpversion)
+CXX_VER=${CXX_VER%%.*}
+if [[ ${CXX_VER} -lt ${MINIMUM_CLANG_VERSION} ]]; then
+  echo "ERROR: clang++ -dumpversion gives '${CXX_VER}', which is less than minimum required '${MINIMUM_CLANG_VERSION}'."
+  exit 1
+fi
+EOF
 
 # Switch to the non-root user.
 USER ${NONROOT_USER}
@@ -108,7 +153,11 @@ WORKDIR /home/${NONROOT_USER}
 ENV CONAN_HOME=/home/${NONROOT_USER}/.conan2
 
 # Create a default Conan profile.
-RUN conan profile detect
+RUN <<EOF
+conan profile detect
+rm -rf /tmp/*
+EOF
+
 # Fix the C++ dialect.
 RUN sed -i -e 's|^compiler\.cppstd=.*$|compiler.cppstd=20|' ${CONAN_HOME}/profiles/default
 # Explicitly set the compiler flags. To ensure compatibility with a range of
@@ -116,15 +165,13 @@ RUN sed -i -e 's|^compiler\.cppstd=.*$|compiler.cppstd=20|' ${CONAN_HOME}/profil
 # of Clang.
 # TODO: Move extra flags into the rippled repository as a custom Conan profile.
 RUN <<EOF
+CXX_VER=$(${CXX} -dumpversion)
+CXX_VER=${CXX_VER%%.*}
 cat >>${CONAN_HOME}/profiles/default <<EOT
 [conf]
 tools.build:compiler_executables={"c": "${CC}", "cpp": "${CXX}"}
 EOT
-if [[ $(clang --version | head -1 | grep -Po 'version \K[0-9]{2}') -ge 20 ]]; then
-    cat >>${CONAN_HOME}/profiles/default <<EOT
-tools.build:cxxflags=['-Wno-missing-template-arg-list-after-template-kw', '-Wno-deprecated-declarations']
-EOT
-elif [[ $(clang --version | head -1 | grep -Po 'version \K[0-9]{2}') -eq 19 ]]; then
+if [[ ${CXX_VER} -ge 19 ]]; then
     cat >>${CONAN_HOME}/profiles/default <<EOT
 tools.build:cxxflags=['-Wno-missing-template-arg-list-after-template-kw']
 EOT
@@ -132,3 +179,10 @@ fi
 EOF
 # Print the Conan profile to verify the configuration.
 RUN conan profile show
+
+# Test the image by compiling a simple C++ program.
+RUN --mount=type=bind,source=test,target=/test,readonly <<EOF
+cp -r /test test
+cd test && ./run.sh && cd ..
+rm -rf test
+EOF
